### ISSUE TITLE
modiying low-gravity plots

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#18]
-I like the low-g objects as colors but please use the same colors for each type as used in the sequence figures. maybe dont use yellow...orange is ok.
-increase line thickness of low gravity objects
-make shading lighter
-try to choose brighter colors as the show up better on top of the gray/black field templates.
-i kinda liked the repetitive label on each sub panel, but maybe if we reduce the number of objects shown, then that wont be necessary.

Let's remove some of the really poor fits
- L0lg - L2 : only compare to L0-L4
- L3 -L4lg  - compare to L1-L5
- L5lg - compare to L2-L7

cccd008acc8bea1e271d496907c99c7c26a71faa

**Comment by kelle** [comment]
What is the grey shading -- is it min-max or 1sigma variance?

**Comment by kelle** [comment]
for L4 and L4 gamma, compare to L2-L7 (instead of L1-L5).

**Comment by kelle** [comment]
consider moving legend from lower left corner to upper left.
consider adding range to legend.

**Comment by alejocosmico** [comment]
Please see comments above.

**Comment by alejocosmico** [comment]
Done.
