### ISSUE TITLE
JK figure needs to be updated

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#25]
The J-K box and whisker plot looks out of date. Not sure how it's generated. For example, number of L4g should be 5 not 6.
https://github.com/alejocosmico/NIRSpecFigures/blob/master/plots/JK.pdf

**Comment by alejocosmico** [comment]
Done.

**Comment by kelle** [comment]
sorry..same issue as with the stats in #26 
- L1 lowg should be 5 (3 gammas + 2 betas) not 4
- L2 lowg should be 2 not 3.

**Comment by alejocosmico** [comment]
Done.
