### ISSUE TITLE
fix L1 field stats

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#28]
L1 should be 18 kept and 3 excluded as listed in these files:
https://github.com/alejocosmico/NIRSpecFigures/blob/master/data/comp_L1_s2.3_band_keepers.txt
https://github.com/alejocosmico/NIRSpecFigures/blob/master/data/comp_L1_s2.3_band_rejects.txt

This affects these the histogram, the J-K distribution, the template, the excluded templates, quartile stats.

**Comment by alejocosmico** [comment]
It would help me a lot if you could clean up the data/ directory. For certain sp-types there is more than one set of files (different chi2 values, e.g. 2.0 and 2.3 for L1 field), and it is not obvious which one goes in the paper. Perhaps just leave in this directory the ones you want to use in the paper.

![screen shot 2015-08-26 at 16 35 55](https://cloud.githubusercontent.com/assets/1479869/9505459/9ae21688-4c10-11e5-8104-491c46bacd6b.jpg)

**Comment by kelle** [comment]
Done. Now there are only two files for each spectral type. and only files  for the spectral types we're including. I think you can regenerate all the figures now.
Figuring out how to do this on github was non-trivial...the command to push deleted files is:
git add . -A

**Comment by alejocosmico** [comment]
I am ALMOST ready to refresh the plots. There is one more table that needs to be updated: data/OptNIR_ALL.txt. I don't remember exactly where this table comes from, but I'm almost certain that you generated it. This table is a key input for the histogram and the J-K plots.

**Comment by kelle** [comment]
I am having to generate this very carefully by hand. I have finished the
field gravity objects, but still need to finish the low gravity (beta and
gammas). stay tuned.

https://docs.google.com/spreadsheets/d/1J19x7ke7I28NIqAch66yRfkTNF7LIWEMklvLWyRg9MQ/edit?usp=sharing

On Tue, Sep 8, 2015 at 4:43 PM, Alejandro Núñez <notifications@github.com>
wrote:

> I am ALMOST ready to refresh the plots. There is one more table that needs
> to be updated: data/OptNIR_ALL.txt. I don't remember exactly where this
> table comes from, but I'm almost certain that you generated it. This table
> is a key input for the histogram and the J-K plots.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alejocosmico/NIRSpecFigures/issues/28#issuecomment-138694112>
> .
>



-- 
Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by kelle** [comment]
ok, this spreadsheet is now ready for you. Could you please generate the CSV file from the Google Spreadsheet.

**Comment by alejocosmico** [comment]
I updated this file in the git using your spreadsheet, and I used it to refresh all relevant plots AND to update numbers in the tex prop tables (both field and low g tables).
