### ISSUE TITLE
fix L3 field figure

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#29]
U50246_0034-0706 is missing from the L3 field template figure.

**Comment by alejocosmico** [comment]
U50246 was not being included because we had no optical spectrum for it. Do you have one now? If yes, send it to me please. If not, is it OK now to include it even though we're missing an optical spectrum?

**Comment by kelle** [comment]
can you make the figure without the optical spectrum? If I recall, the data exist, I just dont have them.

**Comment by kelle** [comment]
Yes, the data exist, I just dont have them. Please make the figure without the optical spectrum.

**Comment by alejocosmico** [comment]
50246 is now included in the L3 template, even though we don't have optical spec.
