### ISSUE TITLE
add 2137+0808 to new NIR spectral standards figure

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#30]
- add U20929 (2137+0808) as a new L5 spectral standard (orange) and compared to the L5 template.
- be sure the L7 plotted is 0825+21. It's an L7.5 but should be compared to the L7.5 template.

**Comment by alejocosmico** [comment]
Confirmed: new standards in templates-stdsL2L7.pdf plot are 0408-1450 (L2), 2137+0808 (L5), and 0825+2115 (L7.5).
