### ISSUE TITLE
L4 dissappears in sequence figure

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#31]
https://github.com/alejocosmico/NIRSpecFigures/blob/master/plots/sequence0_f.pdf
I really like the concept you used here (varying the saturation of the blue) but the light yellow used for L4 is too light. It's fine with me to use the same orange used for L5.

**Comment by alejocosmico** [comment]
OK, I made the field L4 line a brighter orange, same as L5.

**Comment by kelle** [comment]
looks great!
