### ISSUE TITLE
compare all low-gravity templates to later type field objects

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#32]
Currently, the comparison figures mostly compare the low gravity objects to the early type templates (L0-L4). Please make additional figures to compare to the later type templates. I may not include them all in the paper, but would like the option.
Compare:
L0g to L5-L8
L0b to L5-L8
L1g to L5-L8
L1b to L5-L8
L2g to L5-L8
L3g to L6-L8
L4g to L6-L8

**Comment by alejocosmico** [comment]
Done deal. I call them "templates2-L0b.pdf", etc. They are not 100% publishable (some labels could have better placement), so let me know if you decide to include any, and I'll polish them up.
